### ISSUE TITLE
Meta.cpp members not found

### ISSUE THREAD

**Issue by Dragonseel** [cginternals/glbinding#190] opened 2016-07-04 21:25 UTC
When building glbinding I encounter some errors regarding some members of glbinding::Meta.
I attached a txt file containing the errors.

[errormessage.txt](https://github.com/cginternals/glbinding/files/346843/errormessage.txt)

I use Visual Studio 2015 with the msvc 19.0.23506.0
I use CMake 3.3.2 and glbinding-2.1.1

I added glbindings via the add_subdirectory to my CMake project.

I've done nothing else, but when I try to compile my project the errors are generated.

**Comment by scheibel** [comment] 2017-04-12 09:21
We do not recommend using glbinding as subproject via `add_subdirectory`.
However, we tested glbinding in this scenario (explained in more detail in #217) and it works for us.

I'm closing this issue due to its age and our inability to reproduce the problem.
Please reopen if your problem still occurs.

**Closed by scheibel** 2017-04-12 09:21 UTC
Labels: bug, requires decision
