### ISSUE TITLE
CMake 3.1.3 failed for unsupporting compiler AppleClang.

### ISSUE THREAD

**Issue by chelxom** [cginternals/glbinding#209] opened 2016-09-26 15:47 UTC
Hello,

When building glbinding with CMake 3.1.3, I encountered

```
CMake Error at xx/cmake_3.1.3/share/cmake-3.1/Modules/WriteCompilerDetectionHeader.cmake:268 (message):
  Unsupported compiler AppleClang.
Call Stack (most recent call first):
  source/glbinding/CMakeLists.txt:175 (write_compiler_detection_header)
```

It seems that [WriteCompilerDetectionHeader](https://github.com/Kitware/CMake/blob/v3.1.3/Modules/WriteCompilerDetectionHeader.cmake):258 module in CMake 3.1.3 does not declare support for compilers rather than `GNU` and `Clang`. But I find glbinding checks `AppleClang` first in [write_compiler_detection_header](https://github.com/cginternals/glbinding/blob/master/source/glbinding/CMakeLists.txt):178 function and causes that module to raise FATAL_ERROR in line 268.

Thanks

**Comment by scheibel** [comment] 2016-09-27 12:07
Thanks for reporting.
We're already aware of this issue (https://github.com/cginternals/cmake-init/issues/31) and will provide a fix soon.

**Comment by scheibel** [comment] 2016-10-04 09:47
The issue is fixed in cmake-init by now, with the next adaption of glbinding to the current version of cmake-init this issue will be fixed here as well.

**Comment by scheibel** [comment] 2016-11-11 12:37
This should be fixed since yesterday.

**Closed** 2016-11-15 07:45 UTC
