### ISSUE TITLE
GL_BY_STRINGS + Release Mode Hangs When Building

### ISSUE THREAD

**Issue by MasonRemaley** [cginternals/glbinding#118] opened 2015-09-28 21:44 UTC
I'm trying to use `glbinding::Meta::getEnum(...)`, and I'm under the impression that this feature isn't available unless I compile with GL_BY_STRINGS enabled. I downloaded v1.1 of the source and ran cmake with the following options:
`cmake -DOPTION_GL_BY_STRINGS=1 -DCMAKE_BUILD_TYPE=RELEASE ..`

When I then run make, it hangs at 59% every time. I've let it go for 20 minutes or so to no effect except heating up my laptop.
`[ 59%] Building CXX object source/glbinding/CMakeFiles/glbinding.dir/source/Meta_ExtensionsByFunctionString.cpp.o`

If I disable OPTION_GL_BY_STRINGS, or switch CMAKE_BUILD_TYPE to DEBUG, it builds everything fairly quickly without any issues. I'm new to cmake--am I doing something wrong here? Let me know if you need any more info from me.

**Comment by scheibel** [comment] 2015-10-03 11:14
Which compiler do you use?
We actually know of some problems with MSVC and Clang (MSVC is just slow with it's optimization, Clang allocates tons of RAM (>12GB, sometimes 20GB) and eventually ends up swapping, thus making it slow).

**Comment by MasonRemaley** [comment] 2015-10-04 02:19
I'm using Clang so that's probably it--should I work under the assumption that this issue won't go away, or  do you expect it to be resolved eventually?

**Comment by scheibel** [comment] 2015-10-04 08:36
I think you should assume this wouldn't get resolved in the near future as it involves a massive change in the optimization structures of clang (and MSVC).

For Windows the problem is partly solved as we provide binary packages (so only we have to spend the extra 20 minutes of compilation) and for Linux we also strive for binary distribution but it is a more heterogeneous field. As our main distribution channel for OS X is currently homebrew (which compiles everything from source), this wouldn't help any of our Apple users.

**Comment by kateyy** [comment] 2015-10-04 10:04
How about making these optimization flags optional? A CMake switch for LTCG would be nice. This could be used as a workaround for these compiler problems, and I think it would also be useful for developing and testing glbinding (and other cmake-init based projects).

**Comment by cgcostume** [comment] 2015-10-05 00:23
I'll try to move the initialization of the gl_by_string maps from compile time to runtime in the next few days, if this will not work - i'll probably use external files comprising the gl_by_string maps. In both cases the data is loaded lazy at runtime.

**Comment by MasonRemaley** [comment] 2015-10-05 18:49
That sounds great! Let me know if want me to test anything out.

**Comment by cgcostume** [comment] 2015-10-15 10:57
@MasonRemaley, can you please retry, our clang build nodes are working now (they crashed as well before) - i reduced the memory load for compile time.

**Closed** 2015-10-15 10:56 UTC

**Comment by MasonRemaley** [comment] 2015-12-20 22:40
Sorry I never responded to this--this did resolve the issue for me, though the resulting library is about 70mb I'm not sure if that's expected.

**Comment by scheibel** [comment] 2015-12-21 07:48
This size sounds like the Debug build. That is the file size of the Release build?

**Comment by MasonRemaley** [comment] 2015-12-21 11:27
Yup it's a release build, I'm not sure why but the debug build is actually a little smaller--I just noticed that this is only happening when I build as a static library though, and it isn't actually affecting the size of my final executable so while it seems a little weird it doesn't actually have any impact on me.

Static Release Build: 77mb
Static Debug Build: 72.3mb
Dynamic Release Build: 8.3mb
Dynamic Debug Build: 20.6mb

**Comment by scheibel** [comment] 2015-12-21 13:04
Ah you talk about the static library...currently we suggest using the dynamic one as we don't use the static library in our setups.

**Comment by MasonRemaley** [comment] 2015-12-24 05:05
Ah okay, sounds good.
